[assembly: System.Reflection.AssemblyVersion("2.1.0.0")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyCompany("haiou")]
[assembly: System.Reflection.AssemblyProduct("MD5")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 haiou 2014")]
[assembly: System.Reflection.AssemblyTitle("MD5")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("9bbfea42-1088-4f47-a2f2-dfd03cb69187")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]

